IMPLHDRS = hplsupport_BlockCyclicDistArray2dDouble_Impl.h
IMPLSRCS = hplsupport_BlockCyclicDistArray2dDouble_cImpl.c
IORHDRS = hplsupport_BlockCyclicDistArray2dDouble_IOR.h hplsupport_IOR.h
IORSRCS = hplsupport_BlockCyclicDistArray2dDouble_IOR.c
SKELSRCS = hplsupport_BlockCyclicDistArray2dDouble_Skel.c
STUBHDRS = hplsupport.h hplsupport_BlockCyclicDistArray2dDouble.h
STUBSRCS = hplsupport_BlockCyclicDistArray2dDouble_Stub.c
