Paper:
	pdflatex blas2cublas
	bibtex blas2cublas
	pdflatex blas2cublas
	pdflatex blas2cublas

clean:
	rm -f *.aux *.dvi *.bbl *.blg *.log *~ *.out

veryclean:
	rm -f *.aux *.dvi *.bbl *.blg *.log *~ *.out blas2cublas.pdf

