#!/bin/sh

echo "This test checks whether the IOR generated by BRAID and Babel is
compatible by comparing the sizeof() of all the structs"

if [ $# -lt 2 ]; then 
    echo "usage: $0 libC runChapel"
    exit 1
fi


babel=$1
braid=$2

for babel_ior in $babel/*IOR.h; do
  file=`filename $ior`
  braid_ior="$braid/$filename"
  echo "include \"$babel_ior\"" >babel.c
  echo "include \"$braid_ior\"" >braid.c
  echo "include \"common.c\""   >>babel.c
  echo "include \"common.c\""   >>braid.c
  echo "int main() {"           >common.c
  awk -- '
    /^struct .* \{/ { print "printf(\"sizeof(\$1) = %z\", sizeof(\$1));" }
  ' $babel_ior                  >>common.c
  echo "return 0; }"            >>common.c
done

