###
### EXAMPLE SHELL SCRIPT FOR SETTING UP ROSE FOR USE IN COMPOSE
### PROJECTS.  REPLACE INSTALL DIRECTORIES AND JAVA LIBRARY
### LOCATION WITH THOSE ON YOUR MACHINE.  ALSO, MAKE SURE THE
### VERSIONS MATCH YOUR ROSE INSTALLATION.
###
export ROSE_VERSION=latest
export BOOST_VERSION=1_45_0
export BOOSTINSTALL=${HOME}/packages/boost_$BOOST_VERSION/installTree
export ROSEINSTALL=${HOME}/packages/rose-$ROSE_VERSION/compileTree

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/java/jdk1.7.0/jre/lib/i386/server/
export LD_LIBRARY_PATH=$BOOSTINSTALL/lib/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ROSEINSTALL/lib
export PATH=$PATH:$ROSEINSTALL/bin
