#!/bin/sh 
# This is ridiculous, but Automake does not support the $(patsubst _,_,_) idiom.

if [ $# -ne 1 ]; then 
    echo "usage: $0 braid-src-path"
    exit 1
fi
srcdir=$1

SIDL_CLASSES="sidl_BaseClass sidl_BaseException sidl_BaseInterface sidl_CastException sidl_ClassInfo sidl_ClassInfoI sidl_DFinder sidl_DLL sidl_EnfPolicy sidl_Finder sidl_InvViolation sidl_io_Deserializer sidl_io_IOException sidl_io_Serializable sidl_io_Serializer sidl_LangSpecificException sidl_Loader sidl_MemAllocException sidl_NotImplementedException sidl_PostViolation sidl_PreViolation sidl_rmi_BindException sidl_rmi_Call sidl_rmi_ConnectException sidl_rmi_ConnectRegistry sidl_rmi_InstanceHandle sidl_rmi_InstanceRegistry sidl_rmi_Invocation sidl_rmi_MalformedURLException sidl_rmi_NetworkException sidl_rmi_NoRouteToHostException sidl_rmi_NoServerException sidl_rmi_ObjectDoesNotExistException sidl_rmi_ProtocolException sidl_rmi_ProtocolFactory sidl_rmi_Response sidl_rmi_Return sidl_rmi_ServerInfo sidl_rmi_ServerRegistry sidl_rmi_TicketBook sidl_rmi_Ticket sidl_rmi_TimeOutException sidl_rmi_UnexpectedCloseException sidl_rmi_UnknownHostException sidl_RuntimeException sidl_SIDLException"

mkdir -p $srcdir/chpl
echo "# AUTOMATICALLY GENERATED by gen-runtime-deps.sh" >$srcdir/chpl/Makefile.include
printf "CHPL_SIDLSTUB_SRCS ="         >>$srcdir/chpl/Makefile.include
for CLASS in $SIDL_CLASSES; do
    echo " \\"                        >>$srcdir/chpl/Makefile.include
  printf "  chpl/${CLASS}_cStub.c"    >>$srcdir/chpl/Makefile.include
done
echo                                  >>$srcdir/chpl/Makefile.include
printf "CHPL_SIDLSTUB_HDRS ="         >>$srcdir/chpl/Makefile.include
for CLASS in $SIDL_CLASSES; do
    echo " \\"                        >>$srcdir/chpl/Makefile.include
    echo "  chpl/${CLASS}_cStub.h \\" >>$srcdir/chpl/Makefile.include
    echo "  chpl/${CLASS}_Stub.h \\"  >>$srcdir/chpl/Makefile.include
  printf "  chpl/${CLASS}_IOR.h"      >>$srcdir/chpl/Makefile.include
done
echo                                  >>$srcdir/chpl/Makefile.include

mkdir -p $srcdir/upc
echo "# AUTOMATICALLY GENERATED by gen-runtime-deps.sh" >$srcdir/upc/Makefile.include
printf "UPC_SIDLSTUB_SRCS ="          >>$srcdir/upc/Makefile.include
for CLASS in $SIDL_CLASSES; do
    echo " \\"                        >>$srcdir/upc/Makefile.include
  printf "  upc/${CLASS}_Stub.upc"    >>$srcdir/upc/Makefile.include
done
echo                                  >>$srcdir/upc/Makefile.include
printf "UPC_SIDLSTUB_HDRS ="          >>$srcdir/upc/Makefile.include
for CLASS in $SIDL_CLASSES; do
    echo " \\"                        >>$srcdir/upc/Makefile.include
    echo "  upc/${CLASS}_Stub.h \\"   >>$srcdir/upc/Makefile.include
  printf "  upc/${CLASS}_IOR.h"       >>$srcdir/upc/Makefile.include
done
echo "#"                              >>$srcdir/upc/Makefile.include
